### ISSUE TITLE
Smokestack graphs always showing 0 / 0 for loss and count

### ISSUE THREAD

**Issue by vegu** [20c/graphsrv#13]
Originally reported in https://github.com/20c/vaping/issues/13

**Comment by aspiers** [comment]
Thanks a lot but I just upgraded to 1.1.1 and after `iptables -I OUTPUT --destination $host_in_vaping_config -j DROP`, even though the graph correctly stops plotting for that host, the loss counter for that host either stays at `0` or briefly goes to `1` and then reverts back to `0`.  My config includes:

```yaml
plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - vodka
```
So if the `iptables` rule is blocking outgoing ICMP traffic for more than 30 seconds then surely the loss counter should go up to 10 at least?
