### ISSUE TITLE
unable to specify specific graphs in layout.yaml

### ISSUE THREAD

**Issue by telsin** [20c/graphsrv#21]
I'm unable to select a specific chart in layout.yaml. Or at least I'm not able to determine how to specify a graph, documentation for "targets" and "id" is not detailed enough to let me figure out how to do it.

**Comment by vegu** [comment]
What exactly are you trying to do?

**Comment by telsin** [comment]
Trying to place specific vaping graphs in specific spots on a page. There's no documentation for target and id, so I'm guessing that id is just the name of the box in the DOM, but I can't guess how to use target to specify a specific graph. Trying what I think is the name element from the vodka config doesn't work (using same name as appears for the graph name on the page.)

**Comment by vegu** [comment]
Install graphsrv 1.2.0

Then make a second "index" type layout

```
  index_manual:
    type: index
    layout:
    - cols:
      - graph:
          config: multitarget
          fit: 'yes'
          targets: all
          source: latency.public_dns
          id: multitarget-latency.public_dns
        width: 4

      - graph:
          config: multitarget
          fit: 'yes'
          targets: all
          source: latency.transit
          id: multitarget-latency.transit
        width: 4
      
      # empty slot
      - width: 4
      height: 33.3
```

Can test by going to `/view/<layout_name>/all`

Then once happy with it rename it to "index" and remove or rename the default index layout.
